### ISSUE TITLE
How images are displayed

### ISSUE THREAD

**Issue by Gwynnbleid1** [riverdi/riverdi-eve-arduino#3]
Hi

In case of showing logo on display I can understand everything up to this line: 
App_WrCoCmd_Buffer(phost, BITMAP_SOURCE(e->src));
in setup_element from file: App_Common.app

this is called by "setup_element(phost, &el[10]);"

end i can see that in el array, that e->src will be 20646.

I just can't figure out where does this 20646 came from. 

Can you please explain how this works, or point me to some materials that explains this ?

**Comment by riverdi** [comment]
Please install tool Eve Asset Builder.

These  lines there is decompresion of images data (in table logo_graphics) and it's loaded to G_RAM.
Gpu_Hal_WrCmd32(phost,CMD_INFLATE);
Gpu_Hal_WrCmd32(phost,0);
Gpu_Hal_WrCmdBuf(phost, (uint8_t*)logo_graphics, sizeof(logo_graphics));

20646  is address of concrete image.
