### ISSUE TITLE
Adding platformio.ini to be used in VSCode and VSCodium

### ISSUE THREAD

**Issue by robouden** [riverdi/riverdi-eve-arduino#4]
For user of PlatformIO and VSCode/Codium. It would be helpful to add a platform.ini
For example (that worked for me)

[env:esp32]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1

Regards,
Rob Oudendijk

**Comment by lukasz-skalski** [comment]
I'm aware it is old request - just doing some cleanup here :) Closing this Issue because we are trying to keep IDE-specific files out of main repository.
