### ISSUE TITLE
fatal error: EEPROM.h: No such file or directory  #include <EEPROM.h>

### ISSUE THREAD

**Issue by miller-craig** [riverdi/riverdi-eve-arduino#7]
Can you explain where to get the EEPROM.h file from?

**Comment by lukasz-skalski** [comment]
EEPROM.h is a part of built-in eeprom library in Arduino IDE [1]. Please verify your Arduino installation.

[1] https://docs.arduino.cc/learn/built-in-libraries/eeprom
